[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "pt"
  name = "Pt"
  url = "pt"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "相册"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Life"
  url = "gallery/life"

[[main]]
  parent = "gallery"
  name = "Movie"
  url = "gallery/movie"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "contact"
  name = "contact"
  url = "contact"
  weight = 7