[[main]]
  identifier = "about"
  name = "ğŸ¤“\nå…³äº"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "ğŸ“¦å½’æ¡£"
  url = "archive"
  weight = 2

[[main]]
  identifier = "pt"
  name = "ğŸ¤ªPt"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "ğŸ¨ç›¸å†Œ"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "ğŸŒ±Life"
  url = "gallery/life"

[[main]]
  parent = "gallery"
  name = "ğŸ¬Movie"
  url = "gallery/movie"

[[main]]
  identifier = "posts"
  name = "ğŸ§±Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "talks"
  name = "ğŸŒtalks"
  url = "talks"
  weight = 6

[[main]]
  identifier = "resume"
  name = "ğŸ“resume"
  url = "resume"
  weight = 7

[[main]]
  identifier = "showcase"
  name = "ğŸ”—Showcase"
  url = "showcase"
  weight = 8

[[main]]
  identifier = "contact"
  name = "ğŸ“§contact"
  url = "contact"
  weight = 9