[[main]]
  identifier = "about"
  name = "ğŸ¤“å…³äº"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "ğŸ“¦å½’æ¡£"
  url = "archive"
  weight = 2


# [[main]]
#   identifier = "categories"
#   name = "â³åˆ†ç±»"
#   url = "categories"
#   weight = 3

[[main]]
  identifier = "tags"
  name = "ğŸ·ï¸æ ‡ç­¾"
  url = "tags"
  weight = 4


[[main]]
  identifier = "presentation"
  name = "ğŸ”®å¹»ç¯"
  url = "presentation"
  weight = 5

[[main]]
  identifier = "gallery"
  name = "ğŸ¨ç›¸å†Œ"
  url = "gallery"
  weight = 6

[[main]]
  parent = "gallery"
  name = "ğŸŒ±ç”Ÿæ´»"
  url = "gallery/life"

[[main]]
  parent = "gallery"
  name = "ğŸ¬å½±è§†"
  url = "gallery/movie"

[[main]]
  parent = "gallery"
  name = "ğŸ§³å·è¥¿"
  url = "gallery/chuanxi"

[[main]]
  parent = "gallery"
  name = "ğŸŒ†åŒ—äº¬"
  url = "gallery/beijing"
[[main]]
  parent = "gallery"
  name = "ğŸŒ†åŒ—äº¬202409"
  url = "gallery/beijing-202409"

[[main]]
  parent = "gallery"
  name = "ğŸ‡¹ğŸ‡­æ³°å›½æ—…è¡Œ"
  url = "gallery/tailand"

# [[main]]
#   identifier = "posts"
#   name = "ğŸ§±Posts"
#   url = "posts"
#   weight = 5

[[main]]
  identifier = "talks"
  name = "ğŸŒè®¨è®º"
  url = "talks"
  weight = 7

[[main]]
  identifier = "weekly"
  name = "â³weekly"
  url = "weekly"
  weight = 8


# [[main]]
#   identifier = "showcase"
#   name = "ğŸª„å±•ç¤º"
#   url = "showcase"
#   weight = 9

# [[main]]
#   identifier = "contact"
#   name = "ğŸ“§è”ç³»"
#   url = "contact"
#   weight = 9

[[main]]
  identifier = "now"
  name = "ğŸ¤¡ç°åœ¨"
  url = "now"
  weight = 10

[[main]]
  identifier = "message"
  name = "ğŸ“¨ç•™è¨€"
  url = "message"
  weight = 11

# [[main]]
#   identifier = "resume"
#   name = "ğŸ“resume"
#   url = "resume"
#   weight = 12

# [[main]]
#   identifier = "memos"
#   name = "âœï¸memos"
#   url = "memos"
#   weight = 12