logoText = "VictorHong"
logoType = "short" # long, short
description = "The VictorHong`s Blog for Hugo example site."
custom_css = []
custom_js = ["js/custom.js"]
useFaviconGenerator = true # https://www.favicon-generator.org/

themeOptions = ["solarized", "dark", "light", "hacker", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase"] # not allowed page types in archive page

# enableUiAnimation = true
# hideSingleContentsWhenJSDisabled = false

# header
homeHeaderType = "img" # text, img, slide

# menu
# showMobileMenuTerms = ["tags", "categories", "series"]

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami
myname = "VictorHong"
email = "1427298682@qq.com"
whoami = "üìöLearnerü§ìNerdüåêDeveloper"
bioImageUrl = ""
useGravatar = false
location = "ShenZhen, China"
organization = "Hugo"
link = "https://github.com/redisread/HUGO_blog"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = false
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"

# footer
showPoweredBy = false
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
baiduAnalytics = "fd051507caad40b5e1cc04fdc7a47342"
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = true
disqus_shortname = ""
commento = false

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = '‰Ω†ÁöÑappId'
  appKey = '‰Ω†ÁöÑappKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'ËØ¥ÁÇπ‰ªÄ‰πàÂêß...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ÁïÖË®Ä
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # Êù•ÂøÖÂäõ

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:1427298682@qq.com"
  phone = "+8617318062050"
  facebook = ""
  twitter = ""
  github = "https://github.com/VictorHongDream/"
  stack-overflow = ""
  instagram = "https://www.instagram.com/jiahong.wu.581/"
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = "https://www.weibo.com/2587041797/"
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""

[donationOptions]
  enable = false
  alipay = "" 
  wechat = ""
  paypal = ""
  patreon = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
  name = "facebook"
  username = ""
[[share]]
  name = "twitter"
[[share]]
  name = "reddit"
[[share]]
  name = "weibo"