logoText = "VictorHong"
logoType = "short" # long, short
logo = true
description = "VictorHongçš„åšå®¢"

# è®¾ç½®é¦–é¡µæ å±•ç¤ºçš„æ ·å¼ header
homeHeaderType = "img" # text, img, slide
# ç§»åŠ¨ç«¯æ˜¯å¦éšè—header
hideHomeHeaderWhenMobile = false

# è®¾ç½®è‡ªå®šä¹‰çš„æ ·å¼ï¼šcustom_css = ["scss/custom.scss"] and then make file at root/assets/scss/custom.scss
custom_css = ["scss/custom.scss", "css/bb-lmm-mk.css"]

# è®¾ç½®è‡ªå®šä¹‰çš„è„šæœ¬ï¼šcustom_js = ["js/custom.js"] and then make file at root/assets/js/custom.js
custom_js = ["js/custom.js", "js/bb-lmm-mk.js"]

# ä½¿ç”¨å›¾æ ‡åˆå§‹åŒ–
useFaviconGenerator = true # https://www.favicon-generator.org/

# ä¸»é¢˜é€‰é¡¹
themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
# å…è®¸åˆ‡æ¢ä¸»é¢˜
enableThemeChange = true
# ä¸å…è®¸å‡ºç°åœ¨é¦–é¡µçš„é¡µé¢ç±»å‹
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "resume", "publication", "now", "message"]
# ä¸å…è®¸å‡ºç°åœ¨é¦–é¡µä¾§è¾¹æ çš„é¡µé¢ç±»å‹ï¼Œæœ€è¿‘æäº¤å±•ç¤º
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "gallery", "publication", "presentation", "resume", "talks"]
# ä¸å…è®¸åœ¨å½’æ¡£é¡µé¢å±•ç¤ºçš„é¡µé¢ç±»å‹
notAllowedTypesInArchive = ["about", "talks", "showcase"] # not allowed page types in archive page
# ä¸å…è®¸RSSçš„é¡µé¢ç±»å‹
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "showcase", "presentation", "resume", "gallery"]
# æ˜¯å¦å±•ç¤ºç½®é¡¶å¸–å­,pinned: trueå¯ä»¥è®¾ç½®æ–‡ç« ç½®é¡¶
enablePinnedPosts = true

# è§†å›¾å®½åº¦å±•ç¤ºè®¾ç½®
viewportSize = "normal" # widest, wider, wide, normal, narrow

# è®¾ç½®æ–‡ç« åˆ†äº«çš„å›¾ç‰‡å±•ç¤ºï¼Œåœ¨æ¯ç¯‡æ–‡ç« ä¹Ÿå¯ä»¥è®¾ç½®
meta_image = "/images/header/hh.jpg"

# æ˜¯å¦ä½¿ç”¨åŠ è½½åŠ¨ç”»
enableUiAnimation = true

# å¦‚æœä¸º trueï¼Œå½“åœ¨æµè§ˆå™¨ä¸­ç¦ç”¨ javascript æ—¶ï¼Œåšå®¢å†…å®¹å°†è¢«éšè—ã€‚
hideSingleContentsWhenJSDisabled = false

# tagæ ‡è®°æ•°é‡åœ¨5ä»¥ä¸Šæ‰å±•ç¤º
minItemsToShowInTagCloud = 2 # Minimum items to show in tag cloud

# appbar
# é¦–é¡µæ å±•ç¤ºæœç´¢æŒ‰é’®
enableAppbarSearchIcon = true
# é¦–é¡µæ å±•ç¤ºè¯­è¨€é€‰æ‹©
enableAppbarLangIcon = false

# menu ç§»åŠ¨ç«¯å±•ç¤º
# showMobileMenuTerms = ["tags", "categories", "series"]

# body
# åšå®¢æ–‡ç« è·¯å¾„å±•ç¤º
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
# æ‘˜è¦ç±»å‹
summaryShape = "classic" # card, classic, compact
# æœç´¢ç»“æœä½ç½®
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami ä¸ªäººä¿¡æ¯
myname = "VictorHong"
email = "wujiahong2013@gmail.com"
whoami = "ğŸ”©å·¥å…·æ§,âŒ¨ï¸ åç«¯ç¨‹åºå‘˜,ğŸ§ªAI æ¢ç´¢è€…"
bioImageUrl = "/images/whoami/VictorHongAvatar.png"  # ç›¸å¯¹äº static ç›®å½•çš„è·¯å¾„
useGravatar = false
location = "Shenzhen, China"
organization = "Meituan"
link = "https://www.jiahongw.com"

# sidebar ä¾§è¾¹æ 
enableBio = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5 # ä¾§è¾¹æ æœ€å¤šæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"] # minimum h2, maximum h4 in your article
enableSidebarPostsByOrder = false # another lists in the sidebar

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false


# service å¤–éƒ¨æœåŠ¡é…ç½® ç½‘é¡µè®¿é—®å±•ç¤ºè®¾ç½®
baiduAnalytics = "8ac34c9d30985a71517efff22def1592"
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment è¯„è®ºé…ç½®
enableComment = true
disqus_shortname = ""
commento = false

# [gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
#   enable = false
#   owner = "redisread"              # Your GitHub ID
#   repo = "redisread.github.io"               # The repo to store comments
#   clientId = "5880093503923d139adb"           # Your client ID
#   clientSecret = "aa0741ecdc011069553c3c898e8e0f54915af0bb"       # Your client secret

[utterances]       # https://utteranc.es/
  owner = "redisread"              # Your GitHub ID
  repo = "redisread.github.io"               # The repo to store comments
  issueTerm = "title"          # pathname (default), title, url, og:title
  message = ""      # Optional
  link = ""         # Optional

# [gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
#   enable = true
#   owner = "redisread"              #Your GitHub ID
#   repo = "redisread.github.io"               # The repo to store comments
#   clientId = "5880093503923d139adb"           # Your client ID
#   clientSecret = "aa0741ecdc011069553c3c898e8e0f54915af0bb"       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = 'H6qFmM5oh7cl8CiHHUdexKnz-gzGzoHsz'
  appKey = 'LNg1dVRYx2AuR4bd0ay4S8x5'
  notify = true  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'robohash' 
  placeholder = 'Say something...'
  visitor = true

[changyan]
  changyanAppid = ""        # Changyan app id             # ç•…è¨€
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:wujiahong2013@gmail.com"
  # phone = "+8617318062050"
  facebook = ""
  twitter = "https://x.com/VictorHong1022"
  github = "https://github.com/redisread/"
  stack-overflow = ""
  instagram = "https://www.instagram.com/jiahong.wu.581/"
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = "https://www.pinterest.com/VictorHongGG"
  stack-exchange = ""
  telegram = ""
  steam = ""
  # weibo = "https://www.weibo.com/2587041797/"
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  # jike = "https://okjk.co/6kiDCE"

[donationOptions]
  enable = false # if set, the donation button will show up on the single page.
  alipay = "" # Alipay QR Code image (example path: images/donation/alipay-qrcode.png) and put your file at root/static/images/donation/
  wechat = "" # Wechat pay QR Code image (example path: same as above)
  paypal = "" # Paypal URL
  patreon = "" # Patreon URL
  bitcoin = "" # example path: images/donation/bitcoin-code-image.png


[copyrightOptions]
  enableCopyrightLink = false
  copyrightLink = "https://creativecommons.org/licenses/by-nc/4.0/"
  copyrightLinkImage = "/images/CC BY-NC.svg"
  copyrightLinkText = "CC BY-NC 4.0"

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
# [[share]]
#   name = "facebook"
#   username = ""
# [[share]]
#   name = "twitter"
# [[share]]
#   name = "reddit"
# [[share]]
#   name = "csdn"

[[footerLinks]]
  name = "ğŸ¤– AIæ­¦å™¨åº“"
  link = "https://slash.jiahongw.com/s/at"
  description = "AIå·¥å…·é›†åˆ"
  weight = 1
[[footerLinks]]
  name = "ğŸ§  çŸ¥è¯†ç®¡ç†å·¥å…·"
  link = "https://slash.jiahongw.com/s/kt"
  description = "çŸ¥è¯†ç®¡ç†å·¥å…·"
  weight = 2

# è‡ªå®šä¹‰emoji
writtenTimeIcon = "ğŸ“…"
modifiedTimeIcon = "ğŸ“"
readingTimeIcon = "â˜•"
authorIcon = "âœï¸"
pagePvIcon = "ğŸ‘€"
tagIcon = "ğŸ·ï¸"
publicationIcon = "ğŸ“š"
typeIcon = "ğŸ¯"